/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/items/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage 1 Item feed (debug/internal after Stage 2) */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    page_size?: number;
                    source_id?: string;
                    content_type?: components["schemas"]["ContentType"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of Items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ItemsFeedResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sources and feed health */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sources with feed health */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SourcesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage 2+ cluster feed (latest/trending/for_you) */
        get: {
            parameters: {
                query?: {
                    tab?: "latest" | "trending" | "for_you";
                    topic_id?: string;
                    content_type?: components["schemas"]["ContentType"];
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of StoryClusters (cards) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClustersFeedResponse"];
                    };
                };
                /** @description Unauthenticated (only returned when tab=for_you) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a StoryCluster and its evidence list */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cluster detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClusterDetail"];
                    };
                };
                /** @description Cluster has been merged; client should redirect to canonical cluster id */
                301: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RedirectResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{id}/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage 4 update log for a cluster */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cluster updates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClusterUpdatesResponse"];
                    };
                };
                /** @description Cluster has been merged; client should redirect to canonical cluster id */
                301: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RedirectResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List topics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Topics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopicsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topic page (clusters in topic) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Topic detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopicDetail"];
                    };
                };
                /** @description Topic has been merged; client should redirect to canonical topic id */
                301: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopicRedirectResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage 4 lineage nodes/edges for a topic */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lineage graph for topic */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopicLineageResponse"];
                    };
                };
                /** @description Topic has been merged; client should redirect to canonical topic id */
                301: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopicRedirectResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage 2+ search (cluster-first) */
        get: {
            parameters: {
                query: {
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Search results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage 3 glossary lookup (term or alias) */
        get: {
            parameters: {
                query: {
                    term: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Best matching glossary entry */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GlossaryLookupResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic_link/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 5 start email magic-link login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthMagicLinkStartRequest"];
                };
            };
            responses: {
                /** @description Sent (or silently accepted) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMagicLinkStartResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic_link/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 5 verify magic-link token and create a session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthMagicLinkVerifyRequest"];
                };
            };
            responses: {
                /** @description Verified; session created (cookie set) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMagicLinkVerifyResponse"];
                    };
                };
                /** @description Invalid or expired token */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 5 logout (revoke current session) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogoutResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage 5 get the current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/prefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage 5 get user preferences and state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User prefs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserPrefsResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Stage 5 update user preferences */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserPrefsPatchRequest"];
                };
            };
            responses: {
                /** @description Updated prefs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserPrefsResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/user/follows/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 5 follow a topic */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    topic_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Followed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Stage 5 unfollow a topic */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    topic_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unfollowed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/blocks/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 5 block a source */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    source_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Blocked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Stage 5 unblock a source */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    source_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unblocked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/saves/{cluster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 5 save a cluster */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cluster_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Stage 5 unsave a cluster */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cluster_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unsaved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/hides/{cluster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 5 hide a cluster from all feeds */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cluster_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hidden */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Stage 5 unhide a cluster */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cluster_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unhidden */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/saves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage 5 list saved clusters (reading list) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Saved clusters */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserSavesResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/watches/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage 6 list watched clusters */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Watched clusters */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserWatchesResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/watches/clusters/{cluster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 6 watch a cluster (story update alerts) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cluster_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Watched */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Stage 6 unwatch a cluster */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cluster_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unwatched */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 8 user feedback (auth optional) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FeedbackIn"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedbackResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage 10 entities list/search */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    entity_type?: components["schemas"]["EntityType"];
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entities */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntitiesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage 10 entity detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entity detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntityDetail"];
                    };
                };
                /** @description Entity has been merged; client should redirect to canonical entity id */
                301: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntityRedirectResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/follows/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage 10 list followed entities (convenience) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Followed entities */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserFollowedEntitiesResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/follows/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 10 follow an entity */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entity_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Followed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Stage 10 unfollow an entity */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entity_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unfollowed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 5 engagement events (auth optional) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventIn"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventsIngestResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage 8 feedback triage queue */
        get: {
            parameters: {
                query?: {
                    status?: "new" | "triaged" | "resolved" | "ignored";
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Feedback reports */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminFeedbackListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/feedback/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Stage 8 update feedback status */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminFeedbackPatchRequest"];
                };
            };
            responses: {
                /** @description Updated feedback report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedbackReport"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/clusters/{id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 8 merge a cluster into another (creates redirect) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminClusterMergeRequest"];
                };
            };
            responses: {
                /** @description Merge completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminClusterMergeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clusters/{id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 8 split a cluster by extracting items into a new cluster */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminClusterSplitRequest"];
                };
            };
            responses: {
                /** @description Split completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminClusterSplitResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clusters/{id}/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 8 quarantine a cluster (stop auto attachments) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AdminClusterQuarantineRequest"];
                };
            };
            responses: {
                /** @description Quarantined */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clusters/{id}/unquarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 8 unquarantine a cluster */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AdminClusterQuarantineRequest"];
                };
            };
            responses: {
                /** @description Unquarantined */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clusters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Stage 8 manual cluster overrides (citations required) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminClusterPatchRequest"];
                };
            };
            responses: {
                /** @description Updated cluster */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClusterDetail"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/clusters/{id}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Stage 8 set cluster topics (manual + locked) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminSetClusterTopicsRequest"];
                };
            };
            responses: {
                /** @description Updated cluster topics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 8 create a topic */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminTopicCreateRequest"];
                };
            };
            responses: {
                /** @description Created topic */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Topic"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/topics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Stage 8 update a topic (name, description, aliases) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminTopicPatchRequest"];
                };
            };
            responses: {
                /** @description Updated topic */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Topic"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/topics/{id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 8 merge a topic into another (creates redirect) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminTopicMergeRequest"];
                };
            };
            responses: {
                /** @description Merge completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminTopicMergeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lineage/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 8 create a lineage node (paper/model/dataset/method) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminLineageNodeCreateRequest"];
                };
            };
            responses: {
                /** @description Created lineage node */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LineageNode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lineage/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 8 create a lineage edge (evidence required) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminLineageEdgeCreateRequest"];
                };
            };
            responses: {
                /** @description Created lineage edge */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LineageEdge"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 10 create an entity */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntityCreateRequest"];
                };
            };
            responses: {
                /** @description Created entity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Entity"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Stage 10 update an entity */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntityPatchRequest"];
                };
            };
            responses: {
                /** @description Updated entity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Entity"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/entities/{id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 10 merge an entity into another (creates redirect) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntityMergeRequest"];
                };
            };
            responses: {
                /** @description Merge completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminEntityMergeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clusters/{id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Stage 10 set cluster entities (manual + locked) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminSetClusterEntitiesRequest"];
                };
            };
            responses: {
                /** @description Updated cluster entities */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimpleOkResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage 10 create an experiment */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminExperimentCreateRequest"];
                };
            };
            responses: {
                /** @description Created experiment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Experiment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/experiments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Stage 10 update an experiment */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminExperimentPatchRequest"];
                };
            };
            responses: {
                /** @description Updated experiment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Experiment"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/feature_flags/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Stage 10 upsert a feature flag */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminFeatureFlagUpsertRequest"];
                };
            };
            responses: {
                /** @description Updated flag */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeatureFlag"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/source_pack/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin import of a source pack (idempotent upsert) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SourcePack"];
                };
            };
            responses: {
                /** @description Import summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SourcePackImportResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin update a Source (active toggle, metadata) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminSourcePatch"];
                };
            };
            responses: {
                /** @description Updated source */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Source"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/feeds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin update a SourceFeed (active toggle, fetch interval) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminFeedPatch"];
                };
            };
            responses: {
                /** @description Updated feed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SourceFeedHealth"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/ingestion/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin trigger a one-off ingestion run (best-effort) */
        post: {
            parameters: {
                query?: {
                    feed_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminRunResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ContentType: "news" | "press_release" | "preprint" | "peer_reviewed" | "report";
        /** @enum {string} */
        EntityType: "person" | "institution" | "model" | "dataset" | "method" | "venue";
        Source: {
            /** Format: uuid */
            source_id: string;
            name: string;
            homepage_url?: string | null;
            /** @enum {string} */
            source_type: "journalism" | "journal" | "preprint_server" | "university" | "government" | "lab" | "blog";
            /** @enum {string|null} */
            reliability_tier?: "tier1" | "tier2" | "tier3" | null;
            active: boolean;
        };
        SourceFeedHealth: {
            /** Format: uuid */
            feed_id: string;
            feed_url: string;
            /** @enum {string} */
            feed_type: "rss" | "atom" | "api";
            active: boolean;
            fetch_interval_minutes?: number;
            /** Format: date-time */
            last_fetched_at?: string | null;
            last_status?: number | null;
            error_streak?: number;
        };
        SourcesResponse: {
            sources: {
                source: components["schemas"]["Source"];
                feeds: components["schemas"]["SourceFeedHealth"][];
            }[];
        };
        Item: {
            /** Format: uuid */
            item_id: string;
            canonical_url: string;
            url?: string;
            title: string;
            snippet?: string | null;
            author?: string | null;
            /** Format: date-time */
            published_at?: string | null;
            /** Format: date-time */
            fetched_at: string;
            content_type: components["schemas"]["ContentType"];
            paywalled?: boolean | null;
            source: {
                /** Format: uuid */
                source_id: string;
                name: string;
            };
            arxiv_id?: string | null;
            doi?: string | null;
            pmid?: string | null;
        };
        ItemsFeedResponse: {
            page: number;
            results: components["schemas"]["Item"][];
        };
        TopicChip: {
            /** Format: uuid */
            topic_id: string;
            name: string;
            score: number;
        };
        ClusterCard: {
            /** Format: uuid */
            cluster_id: string;
            canonical_title: string;
            /** Format: date-time */
            updated_at: string;
            distinct_source_count: number;
            top_topics?: components["schemas"]["TopicChip"][];
            content_type_badges?: components["schemas"]["ContentType"][];
            method_badges?: string[];
            takeaway?: string | null;
            anti_hype_flags?: string[];
            is_saved?: boolean | null;
            is_watched?: boolean | null;
            why_in_feed?: components["schemas"]["WhyInFeed"];
        };
        ClustersFeedResponse: {
            tab: string;
            page: number;
            results: components["schemas"]["ClusterCard"][];
        };
        EvidenceItem: {
            /** Format: uuid */
            item_id: string;
            title: string;
            url: string;
            /** Format: date-time */
            published_at: string | null;
            source: {
                /** Format: uuid */
                source_id: string;
                name: string;
            };
            content_type?: components["schemas"]["ContentType"];
        };
        ClusterDetail: {
            /** Format: uuid */
            cluster_id: string;
            canonical_title: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            distinct_source_count: number;
            topics?: components["schemas"]["TopicChip"][];
            content_type_breakdown?: {
                [key: string]: number;
            };
            evidence: {
                [key: string]: components["schemas"]["EvidenceItem"][];
            };
            takeaway?: string | null;
            summary_intuition?: string | null;
            summary_deep_dive?: string | null;
            assumptions?: string[];
            limitations?: string[];
            what_could_change_this?: string[];
            method_badges?: string[];
            anti_hype_flags?: string[];
            takeaway_supporting_item_ids?: string[];
            summary_intuition_supporting_item_ids?: string[];
            summary_deep_dive_supporting_item_ids?: string[];
            glossary_entries?: components["schemas"]["GlossaryEntry"][];
            is_saved?: boolean | null;
            is_watched?: boolean | null;
        };
        Topic: {
            /** Format: uuid */
            topic_id: string;
            name: string;
            description_short?: string | null;
            is_followed?: boolean | null;
        };
        TopicsResponse: {
            topics: components["schemas"]["Topic"][];
        };
        TopicDetail: components["schemas"]["Topic"] & {
            latest_clusters: components["schemas"]["ClusterCard"][];
            trending_clusters?: components["schemas"]["ClusterCard"][];
        };
        ClusterUpdateEntry: {
            /** Format: date-time */
            created_at: string;
            /** @enum {string} */
            change_type: "new_evidence" | "refinement" | "contradiction" | "merge" | "split" | "quarantine" | "unquarantine" | "correction";
            summary: string;
            diff?: {
                previously?: string[];
                now?: string[];
                because?: string[];
            } | null;
            supporting_item_ids: string[];
        };
        ClusterUpdatesResponse: {
            /** Format: uuid */
            cluster_id: string;
            updates: components["schemas"]["ClusterUpdateEntry"][];
        };
        LineageNode: {
            /** Format: uuid */
            node_id: string;
            /** @enum {string} */
            node_type: "paper" | "model" | "dataset" | "method";
            title: string;
            external_url?: string | null;
            /** Format: date-time */
            published_at?: string | null;
        };
        LineageEdge: {
            /** Format: uuid */
            from: string;
            /** Format: uuid */
            to: string;
            /** @enum {string} */
            relation_type: "extends" | "improves" | "compresses" | "replaces_in_some_settings" | "contradicts" | "orthogonal";
            evidence_item_ids: string[];
            notes_short?: string | null;
        };
        TopicLineageResponse: {
            /** Format: uuid */
            topic_id: string;
            nodes: components["schemas"]["LineageNode"][];
            edges: components["schemas"]["LineageEdge"][];
        };
        SearchResponse: {
            query: string;
            clusters: components["schemas"]["ClusterCard"][];
            topics?: components["schemas"]["Topic"][];
            entities?: components["schemas"]["Entity"][];
        };
        RedirectResponse: {
            /** Format: uuid */
            redirect_to_cluster_id: string;
        };
        TopicRedirectResponse: {
            /** Format: uuid */
            redirect_to_topic_id: string;
        };
        EntityRedirectResponse: {
            /** Format: uuid */
            redirect_to_entity_id: string;
        };
        GlossaryEntry: {
            /** Format: uuid */
            glossary_entry_id: string;
            term: string;
            definition_short: string;
            definition_long?: string | null;
        };
        GlossaryLookupResponse: {
            entry: components["schemas"]["GlossaryEntry"];
        };
        SourcePack: {
            sources: {
                name: string;
                homepage_url?: string | null;
                /** @enum {string} */
                source_type: "journalism" | "journal" | "preprint_server" | "university" | "government" | "lab" | "blog";
                /** @enum {string|null} */
                reliability_tier?: "tier1" | "tier2" | "tier3" | null;
                active?: boolean | null;
                terms_notes?: string | null;
                feeds: {
                    feed_url: string;
                    /** @enum {string} */
                    feed_type: "rss" | "atom" | "api";
                    fetch_interval_minutes?: number | null;
                    active?: boolean | null;
                }[];
            }[];
        };
        SourcePackImportResponse: {
            sources_upserted: number;
            feeds_upserted: number;
        };
        AdminSourcePatch: {
            name?: string;
            homepage_url?: string | null;
            /** @enum {string} */
            source_type?: "journalism" | "journal" | "preprint_server" | "university" | "government" | "lab" | "blog";
            /** @enum {string|null} */
            reliability_tier?: "tier1" | "tier2" | "tier3" | null;
            terms_notes?: string | null;
            active?: boolean;
        };
        AdminFeedPatch: {
            feed_url?: string;
            /** @enum {string} */
            feed_type?: "rss" | "atom" | "api";
            fetch_interval_minutes?: number;
            active?: boolean;
        };
        AdminRunResponse: {
            /** @enum {string} */
            status: "accepted";
        };
        WhyInFeed: {
            reasons?: string[];
            matched_topic_ids?: string[];
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
        SimpleOkResponse: {
            /** @enum {string} */
            status: "ok";
        };
        User: {
            /** Format: uuid */
            user_id: string;
            email: string;
            /** Format: date-time */
            created_at: string;
        };
        UserResponse: {
            user: components["schemas"]["User"];
        };
        AuthMagicLinkStartRequest: {
            /** Format: email */
            email: string;
        };
        AuthMagicLinkStartResponse: {
            /** @enum {string} */
            status: "sent";
        };
        AuthMagicLinkVerifyRequest: {
            token: string;
        };
        AuthMagicLinkVerifyResponse: {
            user: components["schemas"]["User"];
        };
        LogoutResponse: {
            /** @enum {string} */
            status: "ok";
        };
        UserPrefs: {
            /** @enum {string} */
            reading_mode_default: "intuition" | "deep";
            followed_topic_ids?: string[];
            followed_entity_ids?: string[];
            blocked_source_ids?: string[];
            saved_cluster_ids?: string[];
            hidden_cluster_ids?: string[];
            notification_settings: {
                [key: string]: unknown;
            };
        };
        UserPrefsResponse: {
            prefs: components["schemas"]["UserPrefs"];
        };
        UserPrefsPatchRequest: {
            /** @enum {string} */
            reading_mode_default?: "intuition" | "deep";
            notification_settings?: {
                [key: string]: unknown;
            };
        };
        SavedCluster: {
            /** Format: date-time */
            saved_at: string;
            cluster: components["schemas"]["ClusterCard"];
        };
        UserSavesResponse: {
            saved: components["schemas"]["SavedCluster"][];
        };
        WatchedCluster: {
            /** Format: date-time */
            watched_at: string;
            cluster: components["schemas"]["ClusterCard"];
        };
        UserWatchesResponse: {
            watched: components["schemas"]["WatchedCluster"][];
        };
        Entity: {
            /** Format: uuid */
            entity_id: string;
            entity_type: components["schemas"]["EntityType"];
            name: string;
            description_short?: string | null;
            external_url?: string | null;
        };
        EntityChip: components["schemas"]["Entity"] & {
            is_followed?: boolean | null;
        };
        EntityDetail: components["schemas"]["EntityChip"] & {
            latest_clusters?: components["schemas"]["ClusterCard"][];
            related_entities?: components["schemas"]["EntityChip"][];
        };
        EntitiesResponse: {
            page: number;
            results: components["schemas"]["EntityChip"][];
        };
        UserFollowedEntitiesResponse: {
            entities: components["schemas"]["EntityChip"][];
        };
        AdminEntityCreateRequest: {
            entity_type: components["schemas"]["EntityType"];
            name: string;
            description_short?: string | null;
            external_url?: string | null;
        };
        AdminEntityPatchRequest: {
            entity_type?: components["schemas"]["EntityType"];
            name?: string;
            description_short?: string | null;
            external_url?: string | null;
        };
        AdminEntityMergeRequest: {
            /** Format: uuid */
            to_entity_id: string;
            notes?: string | null;
            supporting_item_ids?: string[];
        };
        AdminEntityMergeResponse: {
            /** Format: uuid */
            from_entity_id: string;
            /** Format: uuid */
            to_entity_id: string;
        };
        AdminSetClusterEntitiesRequest: {
            /** @default true */
            replace: boolean;
            entities: components["schemas"]["AdminClusterEntityAssignment"][];
            notes?: string | null;
        };
        AdminClusterEntityAssignment: {
            /** Format: uuid */
            entity_id: string;
            score?: number | null;
            locked?: boolean | null;
        };
        Experiment: {
            /** Format: uuid */
            experiment_id: string;
            key: string;
            description?: string | null;
            active: boolean;
            /** Format: date-time */
            start_at?: string | null;
            /** Format: date-time */
            end_at?: string | null;
        };
        AdminExperimentCreateRequest: {
            key: string;
            description?: string | null;
            active?: boolean | null;
            /** Format: date-time */
            start_at?: string | null;
            /** Format: date-time */
            end_at?: string | null;
        };
        AdminExperimentPatchRequest: {
            description?: string | null;
            active?: boolean;
            /** Format: date-time */
            start_at?: string | null;
            /** Format: date-time */
            end_at?: string | null;
        };
        FeatureFlag: {
            key: string;
            enabled: boolean;
            config?: {
                [key: string]: unknown;
            };
        };
        AdminFeatureFlagUpsertRequest: {
            enabled?: boolean;
            config?: {
                [key: string]: unknown;
            };
        };
        EventIn: {
            /** @enum {string} */
            event_type: "open_cluster" | "click_item" | "save_cluster" | "unsave_cluster" | "hide_cluster" | "unhide_cluster" | "follow_topic" | "unfollow_topic" | "block_source" | "unblock_source";
            /** Format: uuid */
            client_id?: string | null;
            /** Format: uuid */
            cluster_id?: string | null;
            /** Format: uuid */
            item_id?: string | null;
            /** Format: uuid */
            topic_id?: string | null;
            meta?: {
                [key: string]: unknown;
            };
        };
        EventsIngestResponse: {
            /** @enum {string} */
            status: "accepted";
        };
        FeedbackIn: {
            /** @enum {string} */
            feedback_type: "confusing" | "overstated" | "incorrect" | "missing_context" | "broken_link" | "other";
            /** Format: uuid */
            client_id?: string | null;
            /** Format: uuid */
            cluster_id?: string | null;
            /** Format: uuid */
            item_id?: string | null;
            /** Format: uuid */
            topic_id?: string | null;
            message?: string | null;
        };
        FeedbackResponse: {
            /** @enum {string} */
            status: "accepted";
            /** Format: uuid */
            feedback_id: string;
        };
        FeedbackReport: {
            /** Format: uuid */
            feedback_id: string;
            /** Format: date-time */
            created_at: string;
            /** @enum {string} */
            feedback_type: "confusing" | "overstated" | "incorrect" | "missing_context" | "broken_link" | "other";
            /** @enum {string} */
            status: "new" | "triaged" | "resolved" | "ignored";
            message?: string | null;
            /** Format: uuid */
            cluster_id?: string | null;
            /** Format: uuid */
            item_id?: string | null;
            /** Format: uuid */
            topic_id?: string | null;
            /** Format: uuid */
            user_id?: string | null;
        };
        AdminFeedbackListResponse: {
            page: number;
            results: components["schemas"]["FeedbackReport"][];
        };
        AdminFeedbackPatchRequest: {
            /** @enum {string} */
            status?: "triaged" | "resolved" | "ignored";
            resolution_notes?: string | null;
        };
        AdminClusterMergeRequest: {
            /** Format: uuid */
            to_cluster_id: string;
            notes?: string | null;
            supporting_item_ids?: string[];
        };
        AdminClusterMergeResponse: {
            /** Format: uuid */
            from_cluster_id: string;
            /** Format: uuid */
            to_cluster_id: string;
        };
        AdminClusterSplitRequest: {
            new_cluster_title?: string | null;
            move_item_ids: string[];
            notes?: string | null;
        };
        AdminClusterSplitResponse: {
            /** Format: uuid */
            source_cluster_id: string;
            /** Format: uuid */
            new_cluster_id: string;
        };
        AdminClusterQuarantineRequest: {
            notes?: string | null;
        };
        AdminClusterPatchRequest: {
            canonical_title?: string;
            /** Format: uuid */
            representative_item_id?: string | null;
            takeaway?: string | null;
            takeaway_supporting_item_ids?: string[];
            summary_intuition?: string | null;
            summary_intuition_supporting_item_ids?: string[];
            summary_deep_dive?: string | null;
            summary_deep_dive_supporting_item_ids?: string[];
            assumptions?: string[];
            limitations?: string[];
            what_could_change_this?: string[];
            method_badges?: string[];
            anti_hype_flags?: string[];
        };
        AdminSetClusterTopicsRequest: {
            /** @default true */
            replace: boolean;
            topics: components["schemas"]["AdminClusterTopicAssignment"][];
            notes?: string | null;
        };
        AdminClusterTopicAssignment: {
            /** Format: uuid */
            topic_id: string;
            score?: number | null;
            locked?: boolean | null;
        };
        AdminTopicCreateRequest: {
            name: string;
            description_short?: string | null;
            aliases?: string[];
            /** Format: uuid */
            parent_topic_id?: string | null;
        };
        AdminTopicPatchRequest: {
            name?: string;
            description_short?: string | null;
            aliases?: string[];
            /** Format: uuid */
            parent_topic_id?: string | null;
        };
        AdminTopicMergeRequest: {
            /** Format: uuid */
            to_topic_id: string;
            notes?: string | null;
        };
        AdminTopicMergeResponse: {
            /** Format: uuid */
            from_topic_id: string;
            /** Format: uuid */
            to_topic_id: string;
        };
        AdminLineageNodeCreateRequest: {
            /** @enum {string} */
            node_type: "paper" | "model" | "dataset" | "method";
            title: string;
            external_url?: string | null;
            /** Format: date-time */
            published_at?: string | null;
            external_ids?: {
                [key: string]: unknown;
            };
            topic_ids?: string[];
        };
        AdminLineageEdgeCreateRequest: {
            /** Format: uuid */
            from_node_id: string;
            /** Format: uuid */
            to_node_id: string;
            /** @enum {string} */
            relation_type: "extends" | "improves" | "compresses" | "replaces_in_some_settings" | "contradicts" | "orthogonal";
            evidence_item_ids: string[];
            notes_short?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
